apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: ${namespace}
  labels:
    app: php
spec:
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort